spring:
  datasource:
    url: jdbc:oracle:thin:@oracle.fiap.com.br:1521:ORCL
    username: rm99102
    password: 05102004
  jpa:
    hibernate:
      ddl-auto: update
      open-in-view: false
      show-sql: true